service: rails-serverless-lambda

plugins:
#   - serverless-ruby-layer
#   - serverless-lift
  # - serverless-rack

provider:
  name: aws
  runtime: ruby2.7
  stage: dev
  region: us-east-1
  memorySize: 256
  iam:
    role: arn:aws:iam::872163348003:role/lambda-execution-role
  environment:
    RAILS_ENV: staging

functions:
  createUser:
    handler: app/composites/user/handler/create_user.Handler.process
    events:
      - http:
          method: post
          path: users/create
  listUser:
    handler: app/composites/user/handler/list_user.Handler.process
    events:
      - http:
          method: get
          path: users/list
  updateUser:
    handler: app/composites/user/handler/update_user.Handler.process
    events:
      - http:
          method: put
          path: users/{user_id}/update
          request:
            parameters:
              paths:
                user_id: true
  deleteUser:
    handler: app/composites/user/handler/delete_user.Handler.process
    events:
      - http:
          method: delete
          path: users/{user_id}/delete
          request:
            parameters:
              paths:
                user_id: true